# Specify the version of the Helm chart API
apiVersion: v2  
# Name of the Helm chart
name: flask-app-helm  
# Description of the Helm chart
description: A Helm chart for Kubernetes to learn Argo CD  
# Type of the chart (e.g., application, library)
type: application  
# Version of the Helm chart
version: 0.1.0  
# Version of the application being deployed by the Helm chart
appVersion: "1.0"  
